services:
  app:
    build:
      context: .
      target: dev
    container_name: alfa-leetcode-api-docker
    ports:
      - '3000:3000'
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
